[package]
name = "hexars"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/bin/cli/main.rs"
name = "hexacli"

[[bin]]
path = "src/bin/api/main.rs"
name = "hexapi"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
